In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler ,MinMaxScaler
df = pd.read_csv('kc_house_data-selected-columns.csv')
df.head

FileNotFoundError: [Errno 2] No such file or directory: 'kc_house_data-selected-columns.csv'

In [112]:
import pandas as pd
import numpy as np
newdf = pd.DataFrame(np.random.rand(334,5),index=np.arange(334))
print(newdf)
type(newdf)
newdf.describe()
newdf.dtypes
type(newdf)
newdf.T

            0         1         2         3         4
0    0.954158  0.305364  0.501175  0.826062  0.955617
1    0.632792  0.869022  0.946218  0.859821  0.247235
2    0.313624  0.838017  0.389587  0.326452  0.733027
3    0.757023  0.650072  0.047102  0.817430  0.574836
4    0.009137  0.253367  0.295334  0.975764  0.685292
..        ...       ...       ...       ...       ...
329  0.713829  0.358648  0.634371  0.715716  0.380226
330  0.631078  0.458517  0.601721  0.465796  0.616955
331  0.099424  0.623964  0.999788  0.794438  0.849615
332  0.903955  0.705758  0.377508  0.094671  0.165289
333  0.949890  0.312934  0.484851  0.337917  0.708505

[334 rows x 5 columns]

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.954158,0.632792,0.313624,0.757023,0.009137,0.112660,0.520808,0.802578,0.301068,0.093754,...,0.287097,0.157983,0.670167,0.117344,0.146365,0.713829,0.631078,0.099424,0.903955,0.949890
1,0.305364,0.869022,0.838017,0.650072,0.253367,0.120343,0.697778,0.858779,0.902257,0.657293,...,0.065524,0.902151,0.736604,0.562624,0.427624,0.358648,0.458517,0.623964,0.705758,0.312934
2,0.501175,0.946218,0.389587,0.047102,0.295334,0.466008,0.401490,0.035899,0.831630,0.006280,...,0.370921,0.406418,0.532543,0.472104,0.437180,0.634371,0.601721,0.999788,0.377508,0.484851
3,0.826062,0.859821,0.326452,0.817430,0.975764,0.640044,0.283214,0.222773,0.471295,0.572096,...,0.768163,0.875641,0.748605,0.710456,0.213371,0.715716,0.465796,0.794438,0.094671,0.337917
4,0.955617,0.247235,0.733027,0.574836,0.685292,0.557895,0.328422,0.155043,0.112350,0.600993,...,0.327689,0.892579,0.059556,0.889461,0.577444,0.380226,0.616955,0.849615,0.165289,0.708505

In [ ]:
import pandas as pd
import numpy as np
a = pd.Series(np.random.rand(34))
print(type(a))
print(a)
a.head()

<class 'pandas.Series'>
0     0.209898
1     0.217222
2     0.076564
3     0.113769
4     0.911494
5     0.975589
6     0.020159
7     0.668231
8     0.232353
9     0.257074
10    0.098772
11    0.236035
12    0.287455
13    0.316593
14    0.360014
15    0.748583
16    0.454014
17    0.696416
18    0.830772
19    0.872498
20    0.665626
21    0.107469
22    0.766285
23    0.598997
24    0.406939
25    0.903801
26    0.586837
27    0.649149
28    0.977641
29    0.977141
30    0.277008
31    0.124634
32    0.805581
33    0.806254
dtype: float64

0     0.209898
1     0.217222
2     0.076564
3     0.113769
4     0.911494
5     0.975589
6     0.020159
7     0.668231
8     0.232353
9     0.257074
10    0.098772
11    0.236035
12    0.287455
13    0.316593
14    0.360014
15    0.748583
16    0.454014
17    0.696416
18    0.830772
19    0.872498
20    0.665626
21    0.107469
22    0.766285
23    0.598997
24    0.406939
25    0.903801
26    0.586837
27    0.649149
28    0.977641
29    0.977141
30    0.277008
31    0.124634
32    0.805581
33    0.806254
dtype: float64

In [61]:
import numpy as np
import pandas as pd
dic1 = {
    "name" : ["nikhil", "bishnoi", "bhadu"],
    "rollNo": [29,108, 1929],
    "city": ["fatehabad", "hisar", "sirsa"]
}
df = pd.DataFrame(dic1)
print(df)
# df.to_csv('friendly.csv', index=False)
# df.describe()
harry = pd.read_csv('friendly.csv')
harry['rollNo'][0]
print(harry)
harry.index= ['1st','2nd','3rd']
type(harry )

      name  rollNo       city
0   nikhil      29  fatehabad
1  bishnoi     108      hisar
2    bhadu    1929      sirsa
      name  rollNo       city
0   nikhil     290  fatehabad
1  bishnoi    1080      hisar
2    bhadu   19290      sirsa

pandas.DataFrame

In [97]:
import pandas as pd
import numpy as np
newdf = pd.DataFrame(np.random.rand(6,5),index=np.arange(6))
print(newdf.head())
# newdf.loc[0][0] = "nikhil"
newdf.dtypes
newdf.head()
newdf.index

          0         1         2         3         4
0  0.665819  0.123606  0.891079  0.317174  0.020923
1  0.674681  0.816126  0.716756  0.804058  0.012798
2  0.959817  0.604522  0.904836  0.429027  0.094599
3  0.426864  0.332981  0.311440  0.741787  0.551535
4  0.331727  0.853410  0.681610  0.005711  0.809381

Index([0, 1, 2, 3, 4, 5], dtype='int64')

In [101]:
newdf.columns
newdf.to_numpy()

array([[0.66581924, 0.12360633, 0.89107892, 0.31717378, 0.02092281],
       [0.67468063, 0.81612605, 0.71675568, 0.80405762, 0.01279822],
       [0.95981714, 0.60452154, 0.90483617, 0.42902651, 0.09459941],
       [0.42686443, 0.33298133, 0.31144024, 0.74178742, 0.55153509],
       [0.33172714, 0.85341038, 0.68161032, 0.00571068, 0.80938083],
       [0.2621442 , 0.77882571, 0.90298746, 0.89293436, 0.67501092]])

In [164]:
newdf.sort_index(axis=0 , ascending=True)
newdf.loc[0, 0] = 100
print(newdf.head(2))
newdf.columns= list("ABCDE")
newdf

      name  rollNo       city    state   0
a   nikhil   290.0  fatehabad  haryana NaN
b  bishnoi  1080.0      hisar  haryana NaN

         A        B          C        D      E
a   nikhil    290.0  fatehabad  haryana    NaN
b  bishnoi   1080.0      hisar  haryana    NaN
c    bhadu  19290.0      sirsa  haryana    NaN
0      NaN      NaN        NaN      NaN  100.0

In [127]:
n = pd.DataFrame(np.random.rand(10,9), index=np.arange(10))
n.sort_index(axis=0, ascending=False)
n[0]

0    0.803519
1    0.477300
2    0.764270
3    0.361059
4    0.617423
5    0.615694
6    0.360608
7    0.308190
8    0.849755
9    0.714891
Name: 0, dtype: float64

In [3]:
import pandas as pd
s = pd.Series([10,20,30,40],index=["math", "english", "hindi", "science"])
s

math       10
english    20
hindi      30
science    40
dtype: int64

In [57]:
import pandas as pd
data = {
    'name': ["nikhil", "bishnoi", "bhadu", "rohit"],
    'age': [20, 21, 22,33],
    'rollNo': [29, 30, 31,33]
}
df = pd.DataFrame(data)
df.index = ['a', 'b', 'c','d']
# print(df.head(2))
# print(df.tail(2))
# print(df.shape)
print(df.columns)
print(df.info)

Index(['name', 'age', 'rollNo'], dtype='str')
<bound method DataFrame.info of       name  age  rollNo
a   nikhil   20      29
b  bishnoi   21      30
c    bhadu   22      31
d    rohit   33      33>

In [62]:
# print(df[["name","age"]])
df.iloc[2]
df

      name  age  rollNo
a   nikhil   20      29
b  bishnoi   21      30
c    bhadu   22      31
d    rohit   33      33

In [49]:
print(df.iloc[0])

name      nikhil
age           20
rollNo        29
Name: a, dtype: object

In [162]:
# df.loc[0,0]= 8998
# newdf = df.drop(0, axis=0)
# newdf.head(2)
ndf= df.drop(["state"], axis=1, inplace=True)
print(ndf)
df.loc["a"]
df

None

      name   rollNo       city       0
a   nikhil    290.0  fatehabad     NaN
b  bishnoi   1080.0      hisar     NaN
c    bhadu  19290.0      sirsa     NaN
0      NaN      NaN        NaN  8998.0

In [124]:
# newdf.loc[[1,2],[0,1]]
# newdf

In [163]:
df= pd.read_csv("friendly.csv")
print(df)
df.dtypes
df.shape
df.info()
df.index=["a","b","c"]
df

      name  rollNo       city    state
0   nikhil     290  fatehabad  haryana
1  bishnoi    1080      hisar  haryana
2    bhadu   19290      sirsa  haryana
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   rollNo  3 non-null      int64
 2   city    3 non-null      str
 3   state   3 non-null      str
dtypes: int64(1), str(3)
memory usage: 228.0 bytes

      name  rollNo       city    state
a   nikhil     290  fatehabad  haryana
b  bishnoi    1080      hisar  haryana
c    bhadu   19290      sirsa  haryana

In [152]:
df.loc["a"]
df

      name   rollNo       city    state       0
a   nikhil    290.0  fatehabad  haryana     NaN
b  bishnoi   1080.0      hisar  haryana     NaN
c    bhadu  19290.0      sirsa  haryana     NaN
0      NaN      NaN        NaN      NaN  8998.0

In [132]:
df.columns.to_list()
df.describe()

             rollNo
count      3.000000
mean    6886.666667
std    10748.861955
min      290.000000
25%      685.000000
50%     1080.000000
75%    10185.000000
max    19290.000000